### ISSUE TITLE
Explosives enchants not working

### ISSUE THREAD

**Issue by HuskiiPoki** [TeamVK/Support#2]
**Name of the Plugin**
Token Enchant

**Version of the Plugin**
14.0.5RC2

**SpigotMC account**
Husku

**PayPal account**
arcadia@eco-tabs.eu 
or
burnsoregan@aol.com
i dont remember sorry

**Describe the bug**
None of the custom explosive enchants work. 

**To Reproduce**

**Expected behavior**
Explosions when breaking a block

**Screenshots**

**Server (please complete the following information):**
 - Type: Spigot
 - Version 1.8.8 

**Additional context**

**Comment by vk2gpz** [comment]
can you attach your config?  How are you picking up those exploded blocks?  Do you hear explosion sound?

**Comment by vk2gpz** [comment]
I'm closing this since I've decided not to proceed with using Github for ticketing.
If you can provide the information I've requested, please do so at vk2gpz.freshdesk.com
